-- 1. 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS MDTS;
USE MDTS;

-- 2. 피부 질환 메타데이터 테이블 (HAM_METADATA)
CREATE TABLE IF NOT EXISTS HAM_METADATA (
    lesion_id VARCHAR(50) PRIMARY KEY,
    image_id VARCHAR(50) NOT NULL,
    dx VARCHAR(20) NOT NULL,
    dx_type VARCHAR(30) NOT NULL,
    age FLOAT,
    sex VARCHAR(10),
    localization VARCHAR(50)
);

-- 3. 해양사고 이력 통계 테이블 (ACCIDENT_HISTORY)
CREATE TABLE IF NOT EXISTS ACCIDENT_HISTORY (
    ACCIDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    YEAR INT NOT NULL,
    ACC_TYPE VARCHAR(50) NOT NULL,
    SHIP_TYPE VARCHAR(50) NOT NULL,
    CAUSE VARCHAR(100) NOT NULL,
    CASUALTIES INT DEFAULT 0
);

-- 4. 외상 조치 지침 DB 테이블 (WOUND_GUIDE)
CREATE TABLE IF NOT EXISTS WOUND_GUIDE (
    CAT_ID VARCHAR(20) PRIMARY KEY,
    GUIDE_CODE VARCHAR(20) NOT NULL,
    DX_NAME VARCHAR(50) NOT NULL,
    RISK_LEVEL VARCHAR(10) NOT NULL,
    TREATMENT TEXT NOT NULL
);

-- 5. AI 실시간 진단 결과 기록 테이블 (추가 요구사항 반영)
CREATE TABLE IF NOT EXISTS WOUND_DETECTIONS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    diagnosis VARCHAR(100),
    confidence FLOAT,
    detected_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_synced TINYINT DEFAULT 0
);

-- 6. 사용자 권한 설정
GRANT ALL PRIVILEGES ON MDTS.* TO 'root'@'%' IDENTIFIED BY '12345';
FLUSH PRIVILEGES;
